import fs from 'fs';

const PROJECT_DOMAIN = 'https://sonoliftbr.lovable.app';

function resolveAsset(url: string) {
  if (!url) return '';
  if (url.startsWith('http')) return url;
  // Use absolute URLs for all lovable-uploads to ensure they load in Shopify
  if (url.includes('/lovable-uploads/')) {
    return `https://sonoliftbr.lovable.app${url.startsWith('/') ? '' : '/'}${url}`;
  }
  return PROJECT_DOMAIN + (url.startsWith('/') ? '' : '/') + url;
}

async function generate() {
  console.log('Generating V53 Shopify HTML...');

  const rootContent = fs.readFileSync('src/routes/__root.tsx', 'utf-8');
  
  const utmifyMatch = rootContent.match(/children:\s*`\(function\(\)\{var l_ge=atob\("([^"]+)"\)[^`]+`|children:\s*`([^`]*Utmify[^`]*)`/);
  const utmifyScript = utmifyMatch ? utmifyMatch[0].replace('children: ', '').replace(/`/g, '') : '';
  
  const metaPixelMatch = rootContent.match(/children:\s*`!function\(f,b,e,v,n,t,s\)[^`]+fbq\('track', 'PageView'\);`/);
  const metaPixelScript = metaPixelMatch ? metaPixelMatch[0].replace('children: ', '').replace(/`/g, '') : '';

  let html = '<!DOCTYPE html>\n';
  html += '<html lang="pt-BR">\n';
  html += '<head>\n';
  html += '  <meta charset="UTF-8">\n';
  html += '  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n';
  html += '  <title>SonoLift™ — Kit Facial + Pescoço e Colo por R$ 197</title>\n';
  html += '  \n';
  html += '  <link rel="preconnect" href="https://fonts.googleapis.com">\n';
  html += '  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>\n';
  html += '  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Playfair+Display:ital,wght@0,400;0,500;0,600;0,700;1,400&display=swap" rel="stylesheet">\n';
  html += '  \n';
  html += '  <script src="https://cdn.tailwindcss.com"></script>\n';
  html += '  <script>\n';
  html += '    tailwind.config = {\n';
  html += '      theme: {\n';
  html += '        extend: {\n';
  html += '          colors: { gold: \'#D4AF37\', \'midnight-deep\': \'#0B1B3B\', cream: \'#FCF9F2\', border: \'#e8e2d2\' },\n';
  html += '          fontFamily: { sans: [\'Inter\', \'sans-serif\'], display: [\'Playfair Display\', \'serif\'] },\n';
  html += '          backgroundImage: { \'gold-gradient\': \'linear-gradient(135deg, #D4AF37 0%, #F4D03F 50%, #D4AF37 100%)\' }\n';
  html += '        }\n';
  html += '      }\n';
  html += '    }\n';
  html += '  </script>\n';
  html += '  \n';
  html += '  <script>' + utmifyScript + '</script>\n';
  html += '  <script>' + metaPixelScript + '</script>\n';
  html += '  <noscript><img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=976841758671110&ev=PageView&noscript=1"/></noscript>\n';
  html += '\n';
  html += '  <style>\n';
  html += '    body { background-color: #FCF9F2; color: #0B1B3B; font-family: \'Inter\', sans-serif; margin: 0; }\n';
  html += '    .reveal { opacity: 0; transform: translateY(20px); transition: all 0.8s ease-out; }\n';
  html += '    .reveal.active { opacity: 1; transform: translateY(0); }\n';
  html += '    .hero-gallery img { max-height: 50vh; object-fit: contain; }\n';
  html += '    @media (min-width: 768px) { .hero-gallery img { max-height: 600px; } }\n';
  html += '    .dot-indicator { height: 6px; border-radius: 9999px; }\n';
  html += '    .dot-small { width: 6px; background-color: rgba(11, 27, 59, 0.2); }\n';
  html += '    .dot-large { width: 12px; background-color: #D4AF37; }\n';
  html += '    .dot-small-white { width: 6px; background-color: rgba(255, 255, 255, 0.2); }\n';
  html += '    .dot-large-gold { width: 12px; background-color: #D4AF37; }\n';
  html += '  </style>\n';
  html += '</head>\n';
  html += '<body>\n';
  html += '  <div class="sticky top-0 z-50 bg-black text-white py-2 text-center text-sm font-bold">\n';
  html += '    ⏳ OFERTA RESERVADA POR: <span id="timer">09:59</span>\n';
  html += '  </div>\n';
  html += '\n';
  html += '  <nav class="bg-white border-b py-4 px-6 flex justify-between items-center sticky top-10 z-40">\n';
  html += '    <a href="/" class="font-display text-2xl font-bold">SonoLift™</a>\n';
  html += '    <div class="hidden md:flex gap-6 text-xs font-bold uppercase tracking-widest">\n';
  html += '      <a href="/" class="hover:text-gold transition">Loja</a>\n';
  html += '      <a href="#ciencia" class="hover:text-gold transition">Ciência</a>\n';
  html += '    </div>\n';
  html += '    <a href="#oferta" class="bg-midnight-deep text-white px-4 py-2 rounded-full text-xs font-bold uppercase tracking-widest">Comprar</a>\n';
  html += '  </nav>\n';
  html += '\n';
  html += '  <main>\n';
  html += '    <section id="oferta" class="py-10 px-4 max-w-6xl mx-auto grid md:grid-cols-2 gap-10">\n';
  html += '      <div class="hero-gallery bg-white rounded-3xl p-4 shadow-xl">\n';
  html += '        <img id="mainImage" src="' + resolveAsset('/lovable-uploads/27116790-264f-4d2c-829d-d8122938006e.png') + '" class="w-full">\n';
  html += '        <div class="flex gap-2 mt-4 overflow-x-auto pb-2">\n';
  html += '            <img onclick="document.getElementById(\'mainImage\').src=this.src" src="' + resolveAsset('/lovable-uploads/27116790-264f-4d2c-829d-d8122938006e.png') + '" class="w-16 h-16 rounded-lg border cursor-pointer">\n';
  html += '            <img onclick="document.getElementById(\'mainImage\').src=this.src" src="' + resolveAsset('/lovable-uploads/5d77431e-4361-460d-8547-49f3e4b77f11.png') + '" class="w-16 h-16 rounded-lg border cursor-pointer">\n';
  html += '            <img onclick="document.getElementById(\'mainImage\').src=this.src" src="' + resolveAsset('/lovable-uploads/d3e9c5ed-38e5-408f-89bc-992d9d150bf3.png') + '" class="w-16 h-16 rounded-lg border cursor-pointer">\n';
  html += '            <img onclick="document.getElementById(\'mainImage\').src=this.src" src="' + resolveAsset('/lovable-uploads/5341f237-7f61-4560-93a5-117565c69781.png') + '" class="w-16 h-16 rounded-lg border cursor-pointer">\n';
  html += '        </div>\n';
  html += '      </div>\n';
  html += '\n';
  html += '      <div>\n';
  html += '        <div class="mt-6 flex flex-col items-center sm:items-start">\n';
  html += '            <p class="text-[10px] font-bold uppercase tracking-widest text-gold mb-1">VOCÊ RECEBE HOJE</p>\n';
  html += '            <div class="flex items-center gap-3">\n';
  html += '              <h2 class="font-display text-2xl text-midnight-deep sm:text-3xl">Sistema Facial + Colo</h2>\n';
  html += '              <span class="rounded bg-gold px-2 py-0.5 text-[10px] font-black uppercase tracking-widest text-midnight-deep shadow-sm">GRÁTIS</span>\n';
  html += '            </div>\n';
  html += '            \n';
  html += '            <div class="mt-4 flex flex-col items-center sm:items-start">\n';
  html += '              <p class="text-[13px] text-gray-500 font-medium">Valor total: <span class="line-through decoration-red-600 decoration-1 opacity-70">R$ 397</span></p>\n';
  html += '              <p class="mt-1 text-[11px] font-black uppercase tracking-[0.2em] text-gold">OFERTA ESPECIAL</p>\n';
  html += '              <div class="mt-0 flex items-baseline gap-2">\n';
  html += '                <span class="font-display text-6xl font-extrabold text-gold leading-tight drop-shadow-sm">R$ 197</span>\n';
  html += '              </div>\n';
  html += '              <p class="mt-1 text-[13px] text-midnight-deep font-medium opacity-90">Em até <strong class="text-gold">12x de R$ 16,42</strong> sem juros</p>\n';
  html += '            </div>\n';
  html += '        </div>\n';
  html += '\n';
  html += '        <div class="mt-6 bg-amber-50 border border-amber-200 p-3 rounded-xl text-center font-bold text-amber-900 text-sm">🎁 OFERTA: Kit Rosto + Kit Colo GRÁTIS</div>\n';
  html += '\n';
  html += '        <a href="https://sono-lift.pay.yampi.com.br/r/R558X0P2M5" class="block mt-6 bg-gold-gradient text-midnight-deep text-center py-5 rounded-full font-black text-lg shadow-xl hover:scale-105 transition">GARANTIR MEU KIT + COLO GRÁTIS →</a>\n';
  html += '        \n';
  html += '        <div class="mt-6 flex flex-col items-center justify-center gap-4 sm:flex-row sm:justify-start">\n';
  html += '            <div class="flex items-center gap-2 text-[13px] font-bold uppercase tracking-wider text-midnight-deep opacity-90">\n';
  html += '                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="h-4 w-4 text-gold"><path d="M12 2C9.243 2 7 4.243 7 7V10H6C4.895 10 4 10.895 4 12V20C4 21.105 4.895 22 6 22H18C19.105 22 20 21.105 20 20V12C20 10.895 19.105 10 18 10H17V7C17 4.243 14.757 2 12 2ZM9 7C9 5.346 10.346 4 12 4C13.654 4 15 5.346 15 7V10H9V7ZM12 17C11.172 17 10.5 16.328 10.5 15.5C10.5 14.672 11.172 14 12 14C12.828 14 13.5 14.672 13.5 15.5C13.5 16.328 12.828 17 12 17Z" /></svg>Compra 100% Segura\n';
  html += '            </div>\n';
  html += '        </div>\n';
  html += '\n';
  html += '        <div class="mt-8 flex flex-wrap items-center justify-center gap-4 border-t border-gray-200 pt-6 sm:justify-start">\n';
  html += '            <img src="https://img.icons8.com/color/48/visa.png" class="h-5">\n';
  html += '            <img src="https://img.icons8.com/color/48/mastercard.png" class="h-6">\n';
  html += '            <img src="' + resolveAsset('/lovable-uploads/c1334645-12cf-46d5-a33e-1081a292d37c.png') + '" class="h-5">\n';
  html += '            <img src="' + resolveAsset('/lovable-uploads/489f6631-01cd-4c8d-852b-7c42767df88e.png') + '" class="h-5">\n';
  html += '        </div>\n';
  html += '\n';
  html += '        <div class="mt-8 flex items-center justify-center gap-2 sm:justify-start">\n';
  html += '            <div class="dot-indicator dot-small"></div>\n';
  html += '            <div class="dot-indicator dot-small"></div>\n';
  html += '            <div class="dot-indicator dot-large"></div>\n';
  html += '            <div class="dot-indicator dot-small"></div>\n';
  html += '        </div>\n';
  html += '      </div>\n';
  html += '    </section>\n';
  html += '\n';
  html += '    <section class="bg-white py-16 px-4">\n';
  html += '      <div class="max-w-4xl mx-auto text-center reveal">\n';
  html += '        <h2 class="font-display text-3xl mb-6">Você dorme de lado? O "Inimigo Invisível" do seu colo...</h2>\n';
  html += '        <div class="aspect-[9/16] max-w-[350px] mx-auto rounded-3xl overflow-hidden shadow-2xl relative">\n';
  html += '          <video src="' + resolveAsset('/lovable-uploads/5f946896-1c0c-4389-9b93-b27b0b1473e0.mp4') + '" autoplay loop muted playsinline class="w-full h-full object-cover"></video>\n';
  html += '          <button onclick="this.previousElementSibling.muted = !this.previousElementSibling.muted" class="absolute bottom-4 right-4 bg-black/50 text-white p-2 rounded-full">🔊</button>\n';
  html += '        </div>\n';
  html += '      </div>\n';
  html += '    </section>\n';
  html += '\n';
  html += '    <section class="bg-midnight-deep text-white py-16 px-4">\n';
  html += '      <div class="max-w-6xl mx-auto grid grid-cols-2 md:grid-cols-4 gap-8 text-center reveal">\n';
  html += '        <div><div class="text-4xl font-black text-gold">97%</div><p class="text-xs uppercase mt-2">Pele mais lisa</p></div>\n';
  html += '        <div><div class="text-4xl font-black text-gold">92%</div><p class="text-xs uppercase mt-2">Menos rugas</p></div>\n';
  html += '        <div><div class="text-4xl font-black text-gold">88%</div><p class="text-xs uppercase mt-2">Colo hidratado</p></div>\n';
  html += '        <div><div class="text-4xl font-black text-gold">95%</div><p class="text-xs uppercase mt-2">Recomendariam</p></div>\n';
  html += '      </div>\n';
  html += '    </section>\n';
  html += '  </main>\n';
  html += '\n';
  html += '  <footer class="bg-midnight-deep text-white pt-16 border-t border-white/5">\n';
  html += '    <div class="max-w-6xl mx-auto px-4 pb-12">\n';
  html += '        <div class="grid gap-10 md:grid-cols-3">\n';
  html += '          <div>\n';
  html += '            <p class="font-display text-2xl">SonoLift<sup class="text-gold">™</sup></p>\n';
  html += '            <p class="mt-3 max-w-sm text-sm opacity-70">Sistema de proteção contra as rugas do sono. Silicone médico de alta performance.</p>\n';
  html += '          </div>\n';
  html += '          <div>\n';
  html += '            <p class="text-xs font-semibold uppercase tracking-[0.2em] text-gold">Loja</p>\n';
  html += '            <ul class="mt-4 space-y-2 text-sm opacity-70">\n';
  html += '              <li><a href="#oferta" class="hover:text-gold">Oferta</a></li>\n';
  html += '              <li><a href="#ciencia" class="hover:text-gold">Ciência</a></li>\n';
  html += '              <li><a href="#resultados" class="hover:text-gold">Resultados</a></li>\n';
  html += '            </ul>\n';
  html += '          </div>\n';
  html += '          <div>\n';
  html += '            <p class="text-xs font-semibold uppercase tracking-[0.2em] text-gold">Institucional</p>\n';
  html += '            <ul class="mt-4 space-y-2 text-sm opacity-70">\n';
  html += '              <li><a href="/pages/quem-somos" class="hover:text-gold">Quem somos</a></li>\n';
  html += '              <li><a href="/pages/politica-de-privacidade" class="hover:text-gold">Política de privacidade</a></li>\n';
  html += '              <li><a href="/pages/termos-de-uso" class="hover:text-gold">Termos de uso</a></li>\n';
  html += '            </ul>\n';
  html += '          </div>\n';
  html += '        </div>\n';
  html += '    </div>\n';
  html += '    <div class="border-t border-white/10 py-8">\n';
  html += '        <div class="max-w-6xl mx-auto px-4 flex flex-col md:flex-row items-center justify-between gap-4 text-xs opacity-60">\n';
  html += '            <span>© 2026 SonoLift Beauty LTDA · CNPJ 76.047.876/0001-90</span>\n';
  html += '            <div class="flex items-center justify-center gap-2">\n';
  html += '                <div class="dot-indicator dot-small-white"></div><div class="dot-indicator dot-small-white"></div><div class="dot-indicator dot-large-gold"></div><div class="dot-indicator dot-small-white"></div>\n';
  html += '            </div>\n';
  html += '        </div>\n';
  html += '    </div>\n';
  html += '  </footer>\n';
  html += '\n';
  html += '  <div id="stickyCTA" class="fixed bottom-0 left-0 w-full bg-white border-t p-3 z-[100] transition-transform translate-y-full md:hidden shadow-[0_-8px_30px_rgba(0,0,0,0.12)]">\n';
  html += '    <a href="https://sono-lift.pay.yampi.com.br/r/R558X0P2M5" class="block bg-gold-gradient text-midnight-deep text-center py-4 px-2 rounded-full font-black text-sm uppercase tracking-wide shadow-lg">GARANTIR MEU KIT + COLO GRÁTIS →</a>\n';
  html += '  </div>\n';
  html += '\n';
  html += '  <script>\n';
  html += '    function startTimer(duration, display) {\n';
  html += '      let timer = duration, minutes, seconds;\n';
  html += '      setInterval(function () {\n';
  html += '        minutes = parseInt(timer / 60, 10);\n';
  html += '        seconds = parseInt(timer % 60, 10);\n';
  html += '        display.textContent = (minutes < 10 ? "0" + minutes : minutes) + ":" + (seconds < 10 ? "0" + seconds : seconds);\n';
  html += '        if (--timer < 0) timer = duration;\n';
  html += '      }, 1000);\n';
  html += '    }\n';
  html += '    window.onload = function () {\n';
  html += '      startTimer(600, document.querySelector(\'#timer\'));\n';
  html += '      const observer = new IntersectionObserver((entries) => {\n';
  html += '        entries.forEach(e => { if(e.isIntersecting) e.target.classList.add(\'active\'); });\n';
  html += '      }, { threshold: 0.1 });\n';
  html += '      document.querySelectorAll(\'.reveal\').forEach(el => observer.observe(el));\n';
  html += '      \n';
  html += '      const sticky = document.getElementById(\'stickyCTA\');\n';
  html += '      window.addEventListener(\'scroll\', function() {\n';
  html += '        if (window.scrollY > 600) sticky.style.transform = \'translateY(0)\';\n';
  html += '        else sticky.style.transform = \'translateY(100%)\';\n';
  html += '      });\n';
  html += '    };\n';
  html += '  </script>\n';
  html += '</body>\n';
  html += '</html>';

  fs.writeFileSync('sonolift-shopify-v53.html', html);
  console.log('Success: sonolift-shopify-v53.html generated.');
}

generate();
